{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-api.config-map") -}}
{{- define "aphw-ddi-api.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_CREATE_CONTAINERS: {{ quote .Values.container.azureStorageCreateContainers }}
  ROBOT_SHEET_NAME: {{ quote .Values.container.robotSheetName }}
  ROBOT_IMPORT_POLICE_API_URL: {{ quote .Values.container.robotImportPoliceApiUrl }}
{{- end -}}
