{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-api.config-map") -}}
{{- define "aphw-ddi-api.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_CREATE_CONTAINERS: {{ quote .Values.container.azureStorageCreateContainers }}
  ROBOT_SHEET_NAME: {{ quote .Values.container.robotSheetName }}
  OS_PLACES_API_BASE_URL: {{ quote .Values.container.osPlacesBaseUrl }}
  POLICE_API_BASE_URL: {{ quote .Values.container.policeApiBaseUrl }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  EVENTS_TOPIC_ADDRESS: {{ .Values.container.eventsTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  EVENTS_TOPIC_ADDRESS: {{ quote .Values.container.eventsTopicAddress }}
  {{- end }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  CERTIFICATE_REQUEST_QUEUE: {{ .Values.container.certificateRequestQueue }}-{{ .Values.environmentCode }}
  {{ else }}
  CERTIFICATE_REQUEST_QUEUE: {{ quote .Values.container.certificateRequestQueue }}
  {{- end }}
  OVERNIGHT_JOB_CRONTAB: {{ quote .Values.container.overnightJobCrontab }}
  PARANOID_RETENTION_PERIOD:  {{ quote .Values.container.paranoidRetentionPeriod }}
  FEATURE_FLAG_PURGE_DELETE:  {{ quote .Values.container.featureFlagPurgeDelete }}
{{- end -}}
