{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-api.container-secret") -}}
{{- define "aphw-ddi-api.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  OS_PLACES_API_KEY: {{ .Values.container.osPlacesApiKey | quote }}
  PORTAL_PUBLIC_KEY: {{ .Values.container.publicKeyPortal | quote }}
  ENFORCEMENT_PUBLIC_KEY: {{ .Values.container.publicKeyEnforcement | quote }}
{{- end -}}
