services:
  aphw-ddi-api:
    build:
      context: .
      target: production
    image: aphw-ddi-api
    container_name: aphw-ddi-api
    depends_on:
      - aphw-ddi-api-postgres
      - aphw-ddi-api-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-api-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-aphw-ddi-events}${MESSAGE_QUEUE_SUFFIX}
      CERTIFICATE_REQUEST_QUEUE: ${CERTIFICATE_REQUEST_QUEUE:-aphw-ddi-certificate-request}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      AZURE_STORAGE_CONNECTION_STRING: "UseDevelopmentStorage=true"
      ROBOT_SHEET_NAME: ${ROBOT_SHEET_NAME:-Passed}
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-test}
      OS_PLACES_API_BASE_URL: ${OS_PLACES_API_BASE_URL:-test}
      POLICE_API_BASE_URL: ${POLICE_API_BASE_URL:-test}
      POSTGRES_DB: aphw-ddi
      POSTGRES_HOST: ${POSTGRES_HOST:-aphw-ddi-api-postgres}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      OVERNIGHT_JOB_CRONTAB: ${OVERNIGHT_JOB_CRONTAB:-5 4 * * *}
      OVERNIGHT_EXPORT_BATCH_SIZE: ${OVERNIGHT_EXPORT_BATCH_SIZE:-2000}
      PARANOID_RETENTION_PERIOD: ${PARANOID_RETENTION_PERIOD:-90}
      FEATURE_FLAG_PURGE_DELETE: ${FEATURE_FLAG_PURGE_DELETE:-true}

  aphw-ddi-api-postgres:
    image: postgres:11.22-alpine
    environment:
      POSTGRES_DB: aphw-ddi
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ppp
    volumes:
      - postgres_data:/var/lib/postgres/data

  aphw-ddi-api-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite-blob --skipApiVersionCheck --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: aphw-ddi-api-azurite

volumes:
  postgres_data:
