# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  aphw-ddi-api:
    build:
      target: development
    image: aphw-ddi-api-development
    container_name: aphw-ddi-api-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    depends_on:
        - aphw-ddi-api-azurite
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://aphw-ddi-api-azurite:10000/devstoreaccount1"
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-test}
      OS_PLACES_API_BASE_URL: ${OS_PLACES_API_BASE_URL:-test}
      POLICE_API_BASE_URL: ${POLICE_API_BASE_URL:-test}
      PACT_BROKER_URL: ${PACT_BROKER_URL:-notset}
      PACT_BROKER_USERNAME: ${PACT_BROKER_USERNAME:-notset}
      PACT_BROKER_PASSWORD: ${PACT_BROKER_PASSWORD:-notset}
      FEATURE_FLAG_PURGE_DELETE: ${FEATURE_FLAG_PURGE_DELETE:-true}

  aphw-ddi-api-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0

  aphw-ddi-api-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: