services:
  dangerous-dogs-act-api:
    build:
      context: .
      target: production
    image: dangerous-dogs-act-api
    container_name: dangerous-dogs-act-api
    environment:
      APPINSIGHTS_CLOUDROLE: dangerous-dogs-act-api-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
