# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  dangerous-dogs-act-api:
    build:
      target: development
    image: dangerous-dogs-act-api-development
    container_name: dangerous-dogs-act-api-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
