version: '3.8'

x-common-migration: &common-migration
  POSTGRES_HOST: ${POSTGRES_HOST:-aphw-ddi-api-postgres}
  SCHEMA_ROLE: ${POSTGRES_SCHEMA_ROLE:-postgres}
  SCHEMA_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  SCHEMA_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
  SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}

x-common-postgres: &common-postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: ${POSTGRES_DB:-aphw-ddi}
  POSTGRES_USERNAME: ${POSTGRES_ADMIN_USERNAME:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-ppp}

services:
  database-up:
    image: liquibase/liquibase:4.27.0
    environment:
      << : [*common-migration, *common-postgres]
    entrypoint: >
      sh -c "/scripts/migration/database-up"
    depends_on:
      - aphw-ddi-api-postgres
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/scripts

  database-down:
    image: liquibase/liquibase:4.27.0
    environment:
      << : [*common-migration, *common-postgres]
    entrypoint: >
      sh -c "/scripts/migration/database-down"
    depends_on:
      - aphw-ddi-api-postgres
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/scripts

  aphw-ddi-api-postgres:
    image: postgres:11.22-alpine
    environment: *common-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
