# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aphw-ddi-api:
    build:
      target: development
    image: aphw-ddi-api-development
    container_name: aphw-ddi-api-development
    ports:
      - "3001:3000"
      - "9230:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://aphw-ddi-api-azurite:10000/devstoreaccount1;}
      ROBOT_IMPORT_POLICE_API_URL: ${ROBOT_IMPORT_POLICE_API_URL:-http://host.docker.internal:3000/force}
    depends_on:
      - aphw-ddi-api-azurite

  aphw-ddi-api-azurite:
    command: "azurite-blob --skipApiVersionCheck --loose --blobHost 0.0.0.0 -l data"
    volumes:
      - azurite_data:/opt/azurite/data
    ports:
      - "10000:10000"

  aphw-ddi-api-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  azurite_data:
