jest.setTimeout(30000)
process.env.COOKIE_PASSWORD = 'cookiepasswordcookiepasswordcookiepassword'
process.env.AZURE_STORAGE_ACCOUNT_NAME = 'devstoreaccount1'
process.env.AZURE_STORAGE_CONNECTION_STRING = 'UseDevelopmentStorage=true'
process.env.DDI_API_BASE_URL = 'http://localhost/api'
process.env.OS_PLACES_API_BASE_URL = 'http://localhost/os-places'
process.env.OS_PLACES_API_KEY = 'some-api-key'
process.env.POLICE_API_BASE_URL = 'http://localhost/police'
process.env.ROBOT_SHEET_NAME = 'Passed'
process.env.ROBOT_IMPORT_POLICE_API_URL = 'http://localhost/force'
process.env.PACT_BROKER_URL = 'http://host.docker.internal:9292'
process.env.AUTH_SERVER_HOSTNAME = 'https://authserver.com'
