environment: production
environmentCode:
name: dangerous-dogs-act-api
namespace: dangerous-dogs
workstream: dangerous-dogs
image: dangerous-dogs-act-api

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: dangerous-dogs-act-api-config-map

containerSecret:
  name: dangerous-dogs-act-api-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
