environment: production
environmentCode:
name: aphw-ddi-api
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-api

labels:
  component: service

appInsights:
  connectionString:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: aphw-ddi-api-config-map

containerSecret:
  name: aphw-ddi-api-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  messageQueueHost: namespace.servicebus.windows.net
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageAccountName: dummy
  azureStorageCreateContainers: false
  robotSheetName: Passed
  robotImportPoliceApiUrl: dummy
  eventsTopicAddress: aphw-ddi-events
  overnightJobCrontab: 5 4 * * *

postgresService:
  postgresDb: dangerous_dogs_index
  postgresqlHost: aphw-ddi-api-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

ingress:
  class: nginx
  endpoint: aphw-ddi-api
  server: example.com

aadPodIdentity: true
