#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^dangerous-dogs-act$ --format={{.Name}})" ]; then
  echo "Creating dangerous-dogs-act Docker network"
  docker network create dangerous-dogs-act
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker-compose down
docker-compose -f docker-compose.migrate.yaml down
# Ensure container images are up to date
docker-compose -f docker-compose.migrate.yaml run --rm database-up

docker-compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $args $@
